#!/usr/bin/env bun
/**
 * Export the bundled local server's GraphQL schema (SDL) to docs/api/schema.graphql.
 *
 * The source of truth is the `typeDefs` template literal in
 * `server/src/schema.ts`. We extract it by reading the file rather than
 * importing the module, because importing executes `createSchema(...)`, which
 * pulls in `graphql-yoga` — a server-only dependency that is not installed at
 * the repo root. Reading the literal keeps this script dependency-free and
 * runnable from a fresh checkout.
 *
 * Usage:
 *   bun run sdl            # write docs/api/schema.graphql
 *   bun run sdl -- --check # exit non-zero if the committed file is stale
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..')
const schemaSource = join(repoRoot, 'server', 'src', 'schema.ts')
const outFile = join(repoRoot, 'docs', 'api', 'schema.graphql')

/** Extract the contents of the `typeDefs = /* GraphQL *\/ `...`` template literal. */
function extractTypeDefs(source: string): string {
  const match = source.match(
    /export\s+const\s+typeDefs\s*=\s*\/\*\s*GraphQL\s*\*\/\s*`([\s\S]*?)`/,
  )
  if (!match?.[1]) {
    throw new Error(
      `Could not locate the \`typeDefs\` template literal in ${schemaSource}`,
    )
  }
  // The literal is indented two spaces inside the module; strip that common
  // leading indentation so the emitted SDL is left-aligned.
  const body = match[1].replace(/^\n/, '').replace(/\n\s*$/, '')
  const lines = body.split('\n')
  const indents = lines
    .filter((l) => l.trim().length > 0)
    .map((l) => l.match(/^\s*/)?.[0].length ?? 0)
  const minIndent = indents.length > 0 ? Math.min(...indents) : 0
  return lines.map((l) => l.slice(minIndent)).join('\n')
}

const header = `# Flowy local (bundled) server — GraphQL schema (SDL)
#
# Generated by \`bun run sdl\` from server/src/schema.ts. Do not edit by hand;
# edit the schema and regenerate. See docs/API.md for the full API reference.
`

function buildSdl(): string {
  const source = readFileSync(schemaSource, 'utf8')
  return `${header}\n${extractTypeDefs(source)}\n`
}

const sdl = buildSdl()

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outFile, 'utf8')
  } catch {
    // missing file counts as stale
  }
  if (current !== sdl) {
    console.error(
      `docs/api/schema.graphql is out of date. Run \`bun run sdl\` to regenerate.`,
    )
    process.exit(1)
  }
  console.log('docs/api/schema.graphql is up to date.')
} else {
  writeFileSync(outFile, sdl)
  console.log(`Wrote ${outFile}`)
}
